### ISSUE TITLE
There is a conflict with the plugin Related Discussions

### ISSUE THREAD

**Issue by Litalino** [datlechin/flarum-discussion-overview#8]
There is a conflict with the plugin nearata/flarum-ext-related-discussions https://github.com/Nearata/flarum-ext-related-discussions  and number like "posts[0].likes().length" not show , {user_list} wrong count

```
mount-redraw.js:15 TypeError: e.tags is not a function
    at Z.app.route.discussion (discussionRouting.js:21:49)
    at Function.<anonymous> (routes.ts:59:24)
    at Function.e [as post] (routes.ts:58:9)
    at s.view (DiscussionOverview.tsx:28:32) //line <Link href={app.route.post(lastPost)}>
    at Function.a (render.js:30:16)
    at render.js:482:45
    at p (render.js:419:9)
    at render.js:488:9
    at p (render.js:419:9)
    at f (render.js:302:11)
```

**Comment by datlechin** [comment]
Hi, this should be fixed. Try to update the extension to [v0.1.0](https://github.com/datlechin/flarum-discussion-overview/releases/tag/v0.1.0)
